---
# tasks to configure cobbler

- name: enable apache2 module
  apache2_module:
    state: present
    name: "{{item}}"
  with_items:
    - "{{apache2_module}}"
  become: true
  tags:
    - configure
    - source
  notify:
    - restart apache2

- name: enable apache2 sites
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  become: true
  with_items:
    - { src: '/etc/apache2/conf-available/cobbler.conf',
      dest: '/etc/apache2/conf-enabled/cobbler.conf'}
    - { src: '/etc/apache2/conf-available/cobbler_web.conf',
    dest: '/etc/apache2/conf-enabled/cobbler_web.conf'}
  tags:
    - configure
    - source
  notify:
    - restart apache2

- name: set cobbler secret
  replace:
    path: /usr/local/share/cobbler/web/settings.py
    regexp: "^SECRET_KEY = ''$"
    replace: "SECRET_KEY = '{{cobbler_secret}}'"
    backup: yes
  when: cobbler_secret != "change_it"
  become: true
  notify:
    - restart cobbler

- name: set cobbler admin password
  copy:
    content: |
      cobbler:Cobbler:a2d6bae81669d707b72c0bd9806e01f3
    dest: /etc/cobbler/users.digest
    mode: "u=rw,g=rw=r"
  become: true
  notify:
    - restart cobbler
