---
# tasks to install cobbler

- name: install dependencies
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
   - "{{run_debs}}"
   - "{{build_debs}}"
  become: yes
  tags:
    - install
    - source

- name: create working directory
  file:
    path: "{{working_dir}}"
    state: directory
    mode: 0755
  tags:
    - install
    - source
    - temp_dir

- name: get cobbler from github
  get_url:
    url: "{{cobbler_url}}"
    dest: "{{working_dir}}/cobbler_v{{cobbler_version}}.tar.gz"
    mode: 0664
  tags:
    - install
    - source
    - download

- name: extract cobbler
  unarchive:
    src: "{{working_dir}}/cobbler_v{{cobbler_version}}.tar.gz"
    dest: "{{working_dir}}"
    remote_src: yes
  tags:
    - install
    - source
    - extract

- name: make install cobbler
  make:
    chdir: "{{working_dir}}/cobbler-{{cobbler_version}}"
    target: install
  become: yes
  tags:
    - install
    - source
    - make

# /etc/cobbler/cobblerd.service /var/lib/systemd/.
# sudo systemctl daemon-reload

- name: fix cobbler links
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  become: true
  with_items:
    - { src: '/usr/local/lib/python2.7/dist-packages/cobbler',
      dest: '/usr/lib/python2.7/dist-packages/cobbler'}
    - { src: '/srv/tftp',
    dest: '/var/lib/tftpboot'}
  tags:
    - install
    - source
    - fix_reference
