---
# tasks file for ansible-cobbler

# install from source when from_packet is set to false
- include_tasks: install_src.yml
  when: from_packet == false

# install from packet if from_packet is to true and distribution is Ubunu
- include_tasks: install_ubuntu.yml
  when: from_packet == true && ansible_distribution == 'Ubuntu'

- include_tasks: configure.yml
