Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder "../.", "/etc/ansible/roles/test_role"

  config.vm.provision "shell", inline: <<-SHELL
     apt-add-repository ppa:ansible/ansible
     apt-get update
     apt-get install -y software-properties-common ansible python-passlib
     apt-get -y dist-upgrade
  SHELL

  config.vm.provision "ansible_local", run: "always" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose        = true
    ansible.limit          = "localhost" # or only "nodes" group, etc.
    ansible.inventory_path = "inventory"
  end

end
